title: Exercises with Solutions in Python
description: Exercises with Solutions in Python
theme: just-the-docs

url: https://just-the-docs.github.io

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Set a path/url to a logo that will be displayed instead of the title
logo: "just-the-docs.svg"

# Set a path/url to a favicon that will be displayed by the browser
# favicon_ico: "/assets/images/favicon.ico"
# If the path to your favicon is /favicon.ico, you can leave favicon_ico unset.
favicon_ico:

aux_links:
  Repository: https://github.com/italojsoliveira/python-exercises

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.6.1"
  // _includes/mermaid_config.js
  {
    theme: "forest"
  }
