title: Exercises with Solutions in Python
description: Exercises with Solutions in Python
theme: just-the-docs

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3

url: https://just-the-docs.github.io

aux_links:
  Repository: https://github.com/italojsoliveira/python-exercises
