title: Exercises with Solutions in Python
description: Exercises with Solutions in Python
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Repository: https://github.com/italojsoliveira/python-exercises
